Update ssrp.yml

diff --git a/.github/workflows/ssrp.yml b/.github/workflows/ssrp.yml
--- a/.github/workflows/ssrp.yml
+++ b/.github/workflows/ssrp.yml
@@ -218,10 +218,7 @@ jobs:
           
           download_for_arch "x86_64" "x86_64"
           download_for_arch "aarch64_generic" "a53"
-          echo "查看a53目录"
-          ls a53/
-          echo "查看x86_64目录"
-          ls x86_64/
+          
 
       - name: Parse version from filename
         id: setver
@@ -238,11 +235,55 @@ jobs:
           done
           echo "版本号是：${ssrp_version}"
 
-      - name: Create install.sh 
+      - name: Download mihomo Core
         run: |
-            echo -e "#!/bin/sh\n\nopkg update\nif [ \$? -ne 0 ]; then\n    echo \"update failed\"\n    exit 1\nfi\nopkg install depends/*.ipk --force-depends\nopkg install *.ipk --force-depends" > x86_64/install.sh
-            chmod +x x86_64/install.sh
-            cp x86_64/install.sh a53/
+          download_mihomo () {
+          URL="$1"
+          SAVE_DIR="$2"
+
+          echo "Downloading mihomo to $SAVE_DIR ..."
+          wget -q --show-progress -O "${SAVE_DIR}/mihomo.gz" "$URL"
+          echo
+          }
+
+          download_mihomo \
+          "https://github.com/MetaCubeX/mihomo/releases/download/v1.19.24/mihomo-linux-amd64-compatible-v1.19.24.gz" \
+          "x86_64"
+
+          download_mihomo \
+          "https://github.com/MetaCubeX/mihomo/releases/download/v1.19.24/mihomo-linux-arm64-v1.19.24.gz" \
+          "a53"
+
+          echo "查看a53目录"
+          ls a53/
+          echo "查看x86_64目录"
+          ls x86_64/
+
+      - name: Create install.sh
+        run: |
+              cat > x86_64/install.sh << 'EOF'
+              #!/bin/sh
+
+              opkg update
+              if [ $? -ne 0 ]; then
+                  echo "update failed"
+                  exit 1
+              fi
+
+              opkg install depends/*.ipk --force-depends
+              opkg install *.ipk --force-depends
+
+              # install mihomo core
+                if [ -f mihomo.gz ]; then
+                  echo "Installing mihomo core..."
+                  gzip -dc mihomo.gz > /usr/bin/mihomo || exit 1
+                  chmod +x /usr/bin/mihomo
+                fi
+              
+              EOF
+
+              chmod +x x86_64/install.sh
+              cp x86_64/install.sh a53/
 
       - name: Clone makeself repo
         run: |
